# -*- coding: utf-8 -*-
"""Nithilaselvan_D18_Task 1A_Registration and Login system using Python, file handling

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o7FiRqDmRb_BXHdZFHDu9DV8bb5Z3C3q

**please create the file called "register_details.txt" before running the code because the checking condition will check the the username already exist or not. Thank you..**
"""

import re  #import regular expression 
def register():
  db = open("register_details.txt","r") #read the file "register_details.txt" 
  print("\n......Registration......")
  print("\nThe username(Mail Id) Enter in to correct format")
  print("Example: example@gamil.com....\n")
  username = input("Enter the username(Email Id): ")
  check = "^[a-zA-Z0-9-_]+@[a-zA-Z]+\.[a-z]{1,3}$"  #check the email condtions
  key = []
  value = []
  for i in db:
    a,b = i.split(", ")
    b = b.strip() 
    key.append(a)
    value.append(b)
  data = dict(zip(key,value))

  if re.match(check,username):
    print("\nEnter the password...") 
    print("password must have one digit,one uppercase and one lowercase letter")
    print("one special character and length of password must have between 5 to 16\n")
    password =input("Password: ") 
    confirm_password = input("Confirm Password: ")
    
    

    if password != confirm_password:
      print("password do not match!....  ")
      register()
    else:
      #print(len(password))
      if username in key:
        print("\nGiven username already exist in the file pls enter the new username:\n ")
        register()
      elif len(password)<5 and len(password)>16 :
        print("\nPassword should be the length of between 5 to 16\n")
        register()
      elif not re.search('[0-9]',password):
        print("\nPassword should be atleast one digit\n")
        register()
      elif not re.search('[A-Z]',password):
        print("\nPassword should be atleast one upper case letter: \n ")
        register()
      elif not re.search('[a-z]',password):
        print("\nPassword should be atleast one lowercase letter: \n")
        register()
      elif not re.search('[$@#!*&]',password):
        print("\nPassword should be atlease one special character: \n")
        register()
      else:
        db = open("register_details.txt","a")
        db.write(username+", "+password+"\n")
        db.close()
        print("Successfully Register")
        print("Please login.....\n ")
        login()
  else:
    print("\nThe username(Mail Id) is not correct! Please Enter the Correct Email ID\n")
    register()

def login():
  db = open("register_details.txt","r")
  print("\n......Login........")
  print("\nEnter the username and password")

  username = input("Username: ")
  password = input("Password: ")
  key = []
  value = []
  for i in db:
    a,b = i.split(", ")
    b = b.strip() 
    key.append(a)
    value.append(b)
  data = dict(zip(key,value))


  if (username, password) in data.items():
    print("\nlogin success\n")
    print("Welcome "+username)
  else:
    print("\nThe username or password incorrect")
    print("\nplease kindly check the username or password\n")
    print("....'If you dont have account pls kindly register'.....\n")
    
    val = int(input("1.login\n2.register\n3.Forget password\nEnter the number"))
    if val == 1:
      login()
    elif val == 2:
      register()
    elif val == 3:
      if username in key:
        print("\nYour password is: "+'\033[1m'+data[username]+'\033[0m')
        print("please remember your password and login again")
        login()
      else:
        print("\nGiven Username not exist in the file pleas enter the correct username..")
        login()
    else:
      print("enter the correct number...")



  

def reg_log():
  print(".......Registration and Login System......")
  print("Login if you already have account or else register first and then login\n")
  print("1.login\n2.Register\nEnter the number")
  log = int(input())
  if log == 1:
    login()
  elif log == 2:
    register()
  else:
    print("Enter the correct number...")

reg_log()

import re  #import regular expression 
def register():
  db = open("register_details.txt","r") #read the file "register_details.txt" 
  print("\n......Registration......")
  print("\nThe username(Mail Id) Enter in to correct format")
  print("Example: example@gamil.com....\n")
  username = input("Enter the username(Email Id): ")
  check = "^[a-zA-Z0-9-_]+@[a-zA-Z]+\.[a-z]{1,3}$"  #check the email condtions
  key = []
  value = []
  for i in db:
    a,b = i.split(", ")
    b = b.strip() 
    key.append(a)
    value.append(b)
  data = dict(zip(key,value))

  if re.match(check,username):
    print("\nEnter the password...") 
    print("password must have one digit,one uppercase and one lowercase letter")
    print("one special character and length of password must have between 5 to 16\n")
    password =input("Password: ") 
    confirm_password = input("Confirm Password: ")
    
    

    if password != confirm_password:
      print("password do not match!....  ")
      register()
    else:
      #print(len(password))
      if username in key:
        print("\nGiven username already exist in the file pls enter the new username:\n ")
        register()
      elif len(password)<5 and len(password)>16 :
        print("\nPassword should be the length of between 5 to 16\n")
        register()
      elif not re.search('[0-9]',password):
        print("\nPassword should be atleast one digit\n")
        register()
      elif not re.search('[A-Z]',password):
        print("\nPassword should be atleast one upper case letter: \n ")
        register()
      elif not re.search('[a-z]',password):
        print("\nPassword should be atleast one lowercase letter: \n")
        register()
      elif not re.search('[$@#!*&]',password):
        print("\nPassword should be atlease one special character: \n")
        register()
      else:
        db = open("register_details.txt","a")
        db.write(username+", "+password+"\n")
        db.close()
        print("Successfully Register")
        print("Please login.....\n ")
        login()
  else:
    print("\nThe username(Mail Id) is not correct! Please Enter the Correct Email ID\n")
    register()

def login():
  db = open("register_details.txt","r")
  print("\n......Login........")
  print("\nEnter the username and password")

  username = input("Username: ")
  password = input("Password: ")
  key = []
  value = []
  for i in db:
    a,b = i.split(", ")
    b = b.strip() 
    key.append(a)
    value.append(b)
  data = dict(zip(key,value))


  if (username, password) in data.items():
    print("\nlogin success\n")
    print("Welcome "+username)
  else:
    print("\nThe username or password incorrect")
    print("\nplease kindly check the username or password\n")
    print("....'If you dont have account pls kindly register'.....\n")
    
    val = int(input("1.login\n2.register\n3.Forget password\nEnter the number"))
    if val == 1:
      login()
    elif val == 2:
      register()
    elif val == 3:
      if username in key:
        print("\nYour password is: "+'\033[1m'+data[username]+'\033[0m')
        print("please remember your password and login again")
        login()
      else:
        print("\nGiven Username not exist in the file pleas enter the correct username..")
        login()
    else:
      print("enter the correct number...")



  

def reg_log():
  print(".......Registration and Login System......")
  print("Login if you already have account or else register first and then login\n")
  print("1.login\n2.Register\nEnter the number")
  log = int(input())
  if log == 1:
    login()
  elif log == 2:
    register()
  else:
    print("Enter the correct number...")

reg_log()